// Type declarations for @liquicode/jsonstor-browser
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// The browser storages: local storage, the Origin Private File System, and IndexedDB.

declare module '@liquicode/jsonstor-browser'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** ***`jsonstor-browser-localstorage` only.*** The `localStorage` key this collection is stored under. One key holds one collection; name a second key for a second collection. */
		Key: string;
		/** ***`jsonstor-browser-opfs` only.*** The path within the Origin Private File System holding this collection. Folders along it are created as needed. */
		Path: string;
		/** ***`jsonstor-browser-indexeddb` only.*** The IndexedDB database holding this collection. It is created if it does not exist. */
		DatabaseName: string;
		/** ***`jsonstor-browser-indexeddb` only.*** The object store this storage reads and writes. One database holds as many collections as you name. */
		CollectionName: string;
		/** ***The two blob storages only.*** Write the collection out after every insert, update, replacement or delete. Turn it off to batch a run of writes and call `FlushStorage()` yourself. `jsonstor-browser-indexeddb` writes a record at a time and has nothing to flush. Defaults to `true`. */
		AutoFlush?: boolean;
		/** The document field which is the identifier. Name the field an existing store is already keyed on to read one. Defaults to `"_id"`. */
		PrimaryKey?: string;
		/** Allow an update or a replacement to change the identifier. Off by default, so an operation which would move it is refused by name rather than silently discarded. Defaults to `false`. */
		PrimaryKeyMutable?: boolean;
		/** ***The two blob storages only.*** Hold an index over the identifier, so a lookup by it costs one entry rather than the whole collection. Off by default, because an index over a store something else writes goes stale - call `RefreshIndex()` when it might have. `jsonstor-browser-indexeddb` hosts its own index and takes no such setting. Defaults to `false`. */
		HostIndex?: boolean;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** `'jsonstor-browser'`. The package's bare name, which `Aliases` maps onto a prime. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
		/** This package's prime versions, each registering under its own name. */
		Adapters: StorageAdapter[];
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-browser.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];
	export const Adapters: StorageAdapter[ 'Adapters' ];

}
